name: github pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.14.3
        uses: actions/setup-go@v2
        with:
          go-version: 1.14.3

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Coverage
        run: |
          go test -coverpkg ./internal/...  -coverprofile=coverage.out ./test/...
          go tool cover -html=coverage.out -o coverage.html
          go run cover.go
          mkdir public
          mv coverage.html ./public/coverage.html
          mv my_coverage.html ./public/index.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./public
